---

- name: plugins > Plugins
  elasticsearch_plugin:
    name:       "{{ item.name }}"
    plugin_bin: "{{ item.plugin_bin|default(elao_elasticsearch_dir ~ '/bin/plugin') }}"
    plugin_dir: "{{ item.plugin_dir|default(elao_elasticsearch_dir ~ '/plugins/') }}"
    timeout:    "{{ item.timeout|default(omit) }}"
    url:        "{{ item.url|default(omit) }}"
    version:    "{{ item.version|default(omit) }}"
    state:      "{{ item.state|default('present') }}"
  with_items: "{{ elao_elasticsearch_plugins }}"
